version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
  ServerStart:
    - location:  scripts/start_nginx.sh
  ApplicationStart:
    - location:  scripts/start_script.sh
