version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  # AfterInstall:
  #   - location: scripts/install_dependencies.sh
  #     timeout: 100
  #   - location: scripts/start_nginx.sh
  #     timeout: 100

  ApplicationStart:
    - location: scripts/build_reactscripts.sh
      timeout: 3600
    - location: scripts/start_script.sh
      timeout: 3600
