version: 0.2  
phases:  
  install:  
    commands:  
      - apt-get update
      - apt-get install nodejs-dev node-gyp libssl1.0-dev -y
      - apt-get install nodejs -y
      - apt-get install npm -y
      - apt-get install nginx -y

  pre_build:
    commands:
      - unlink /etc/nginx/sites-enabled/default
      - cp nginx2.conf /etc/nginx/sites-available
      - ln -s /etc/nginx/sites-available/nginx2.conf /etc/nginx/sites-enabled/nginx2.conf
      - nginx -t

  build:  
    commands:  
      - cd pages 
      - echo `pwd` 
      - npm install
      - npm run build
      - cd ..
      - echo `pwd`
      - npm install
      - node server.js   

artifacts:  
  files:  
      - '**/*'