version: 0.2  
phases:  
  install:  
    commands:  
      - apt-get update
      - apt-get install nodejs-dev node-gyp libssl1.0-dev -y
      - apt-get install nodejs -y
      - apt-get install npm -y

  build:  
    commands:  
      - cd pages && npm install && npm run build
      - cd .. && npm install

artifacts:  
  files:  
      - '**/*'